name: Run tests on Java 8

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    name: Run tests on Java 17
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          distribution: 'oracle'
          java-version: '17'
      - run: mvn -f pom.xml test