name: deploy
on:
  push:
    branches:
      - main
      - dev

jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Unit Tests
        run: mvn clean package

      - name: Rename the artifact
        run: cp target/university-simulation-1.0-SNAPSHOT.jar university-simulation-${{ github.sha }}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: university-simulation
          path: university-simulation-${{ github.sha }}.jar

  fake-deploy:
    runs-on: self-hosted
    needs: run-unit-tests
    steps:
      - name: Get the artifact
        uses: actions/download-artifact@master
        with:
          name: university-simulation

      - name: Fake deploy
        run: ls university-simulation-*.jar
