name: only-tests
on:
  push:
    branches:
      - main
      - dev

jobs:
  run-all-tests:
    runs-on: self-hosted
    steps:
      - name: Test SSH access
        run: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Checkout
        uses: actions/checkout@v3

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: All the Tests and Coverage check
        run: mvn clean install